### ISSUE TITLE
Issue when running ssh tests

### ISSUE THREAD

**Issue by cournape** [blaze/odo#196] opened 2015-05-12 15:59 UTC
I see what looks like a deadlock when running the test suite with paramiko installed, on linux + 2.7:

```
py.test --collect-only odo/
...
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collecting 175 items / 12 skipped
```

I suspect a deadlock because the issue disappears iff I remove the `ssh.connect` in https://github.com/ContinuumIO/odo/blob/master/odo/backends/tests/test_ssh.py#L24, and strace shows a litany of:

```
[pid 10354] futex(0x180ef0a0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10381] futex(0x180ef0a0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10354] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10381] <... futex resumed> )       = 0
[pid 10354] select(0, NULL, NULL, NULL, {0, 8000} <unfinished ...>
[pid 10381] select(0, NULL, NULL, NULL, {0, 100000} <unfinished ...>
[pid 10354] <... select resumed> )      = 0 (Timeout)
[pid 10354] select(0, NULL, NULL, NULL, {0, 16000}) = 0 (Timeout)
[pid 10354] select(0, NULL, NULL, NULL, {0, 32000}) = 0 (Timeout)
[pid 10354] select(0, NULL, NULL, NULL, {0, 34890}
```

You may not want to do network IO in imports, as this may cause some thread creation (https://docs.python.org/2/library/threading.html#importing-in-threaded-code). I would suggest to instead implement the skip functionality using memoization.

**Comment by cpcloud** [comment] 2015-05-12 16:04
i think a `module` scoped fixture would also do the trick

**Comment by cpcloud** [comment] 2015-05-12 16:11
Hm, I can't reproduce this on OS X. It takes a long time, but it doesn't hang indefinitely.

**Comment by cpcloud** [comment] 2015-07-01 20:00
@cournape would you care to put up a solution for this? i'm having trouble reproducing it

**Comment by kwmsmith** [comment] 2016-02-02 18:27
@cournape I'm closing this issue due to the time lag and our inability to reproduce; if you're still seeing this bug, please re-open.

**Closed by kwmsmith** 2016-02-02 18:27 UTC
Labels: bug
