### ISSUE TITLE
ODO unable to read pytable carray

### ISSUE THREAD

**Issue by supriyom083** [blaze/odo#297] opened 2015-08-23 17:46 UTC
import numpy
import tables
from  odo import odo
fileName = 'carray1.h5'
shape = (200, 300)
atom = tables.UInt8Atom()
filters = tables.Filters(complevel=5, complib='zlib')

h5f = tables.open_file(fileName, 'w')
ca = h5f.create_carray(h5f.root, 'carray', atom, shape,
                       filters=filters)

# Fill a hyperslab in ``ca``.
ca[10:60, 20:70] = numpy.ones((50, 50))
ca
h5f.close()

# Re-open a read another hyperslab
h5f = tables.open_file(fileName)
print(h5f)
print(h5f.root.carray[8:12, 18:22])
h5f.close()
#discover(ca)    
#ds = dshape("var * {name: float64, balance: float64")

h5f.close()

odo('pytables://carray1.h5::/carray','a.csv',dshape='var * {name: float64, balance: float64}')

OUTPUT:

carray1.h5 (File) ''
Last modif.: 'Sun Aug 23 20:43:04 2015'
Object Tree: 
/ (RootGroup) ''
/carray (CArray(200, 300), shuffle, zlib(5)) ''

[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 1]
 [0 0 1 1]]
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-17-af30ec936fbb> in <module>()
     28 
     29 
---> 30 odo('pytables://carray1.h5::/carray','a.csv',dshape='var * {name: float64, balance: float64}')

C:\Anaconda\lib\site-packages\odo\odo.pyc in odo(source, target, **kwargs)
     88     odo.append.append      - Add things onto existing things
     89     """
---> 90     return into(target, source, **kwargs)

C:\Anaconda\lib\site-packages\multipledispatch\dispatcher.pyc in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

C:\Anaconda\lib\site-packages\odo\into.pyc in into_string_string(a, b, **kwargs)
    117 @into.register((type, str), str)
    118 def into_string_string(a, b, **kwargs):
--> 119     r = resource(b, **kwargs)
    120     return into(a, r, **kwargs)
    121 

C:\Anaconda\lib\site-packages\odo\regex.pyc in __call__(self, s, *args, **kwargs)
     62 
     63     def __call__(self, s, *args, **kwargs):
---> 64         return self.dispatch(s)(s, *args, **kwargs)
     65 
     66     @property

C:\Anaconda\lib\site-packages\odo\resource.pyc in resource_split(uri, *args, **kwargs)
    104 def resource_split(uri, *args, **kwargs):
    105     uri, other = uri.rsplit('::', 1)
--> 106     return resource(uri, other, *args, **kwargs)

C:\Anaconda\lib\site-packages\odo\regex.pyc in __call__(self, s, *args, **kwargs)
     62 
     63     def __call__(self, s, *args, **kwargs):
---> 64         return self.dispatch(s)(s, *args, **kwargs)
     65 
     66     @property

C:\Anaconda\lib\site-packages\odo\backends\pytables.pyc in resource_pytables(path, datapath, **kwargs)
    149 @resource.register('pytables://.+', priority=11)
    150 def resource_pytables(path, datapath, **kwargs):
--> 151     return PyTables(path, datapath, **kwargs)
    152 
    153 

C:\Anaconda\lib\site-packages\odo\backends\pytables.pyc in PyTables(path, datapath, dshape, **kwargs)
    143         with tmpfile('.h5') as filename:
    144             possibly_create_table(filename, dtype)
--> 145             shutil.copyfile(filename, path)
    146     return tables.open_file(path, mode='a').get_node(datapath)
    147 

C:\Anaconda\lib\shutil.pyc in copyfile(src, dst)
     81 
     82     with open(src, 'rb') as fsrc:
---> 83         with open(dst, 'wb') as fdst:
     84             copyfileobj(fsrc, fdst)
     85 

IOError: [Errno 22] invalid mode ('wb') or filename: 'pytables://carray1.h5'

**Comment by cpcloud** [comment] 2015-08-24 01:10
this is a duplicate of #292

**Comment by cpcloud** [comment] 2015-08-24 01:11
please try with current master and reopen if that doesn't work. thanks

**Closed by cpcloud** 2015-08-24 01:10 UTC
Labels: duplicate
